language: php
sudo: false

before_install:
    - composer self-update

install:
    - composer install
    - ./bin/phpunit install

matrix:
    fast_finish: true
    include:
        - php: 5.3
        - php: 5.4
        - php: 5.5
        - php: 5.6
        - php: 7.0
        - php: 7.1
        - php: 7.1
        - php: 7.2
        - php: nightly
        - php: hhvm
    allow_failures:
        - php: nightly

script:
  - echo tests
